add_executable(n-queens-1 n-queens-1.cpp)
add_executable(sudoku-solver-1 sudoku-solver-1.cpp)
add_executable(word-search-2 word-search-2.cpp)
add_executable(palindrome-partitioning-1 palindrome-partitioning-1.cpp)
add_executable(expression-add-operators-1 expression-add-operators-1.cpp)
add_executable(remove-invalid-parentheses-1 remove-invalid-parentheses-1.cpp)
add_executable(regex-matching-1 regex-matching-1.cpp)
add_executable(unique-paths-2 unique-paths-2.cpp)
add_executable(skyline-problem-1 skyline-problem-1.cpp)
add_executable(tower-of-hanoi-with-constraints tower-of-hanoi-with-constraints.cpp)