add_executable(n-queens n-queens.cpp)
add_executable(sudoku-solver-1 sudoku-solver-1.cpp)
add_executable(word-search-2 word-search-2.cpp)
add_executable(palindrome-partitioning-2 palindrome-partitioning-2.cpp)
add_executable(expression-add-operators expression-add-operators.cpp)
add_executable(remove-invalid-parentheses remove-invalid-parentheses.cpp)
add_executable(regex-matching-1 regex-matching-1.cpp)
add_executable(unique-paths-3 unique-paths-3.cpp)
add_executable(skyline-problem-1 skyline-problem-1.cpp)
add_executable(tower-of-hanoi-with-constraints tower-of-hanoi-with-constraints.cpp)