add_executable(max-product-of-two-eles-array max-product-of-two-eles-array.cpp)
add_executable(intersection-of-two-arrays-2 intersection-of-two-arrays-2.cpp)
add_executable(sorted-and-rotated sorted-and-rotated.cpp)
add_executable(numbers-disappeared-in-an-array numbers-disappeared-in-an-array.cpp)
add_executable(contains-duplicate-2 contains-duplicate-2.cpp)
add_executable(max-avg-subarray-1 max-avg-subarray-1.cpp)
add_executable(monotonic-array monotonic-array.cpp)
add_executable(can-place-flowers-1 can-place-flowers-1.cpp)
add_executable(common-characters common-characters.cpp)
add_executable(left-and-right-sum-diff left-and-right-sum-diff.cpp)