add_executable(orderly-queue orderly-queue.cpp)
add_executable(shortest-palindrome shortest-palindrome.cpp)
add_executable(distinct-subsequences distinct-subsequences.cpp)
add_executable(text-justification text-justification.cpp)
add_executable(wildcard-matching wildcard-matching.cpp)
add_executable(word-ladder-1 word-ladder-1.cpp)
add_executable(palindrome-partitioning-3 palindrome-partitioning-3.cpp)
add_executable(regex-matching-2 regex-matching-2.cpp)
add_executable(min-window-subsequence min-window-subsequence.cpp)
add_executable(advanced-substring-match-with-displacements advanced-substring-match-with-displacements.cpp)