add_executable(max-gap max-gap.cpp)
add_executable(longest-common-subpath longest-common-subpath.cpp)
add_executable(min-initial-energy-to-complete-tasks-1 min-initial-energy-to-complete-tasks-1.cpp)
add_executable(number-of-wiggle-subsequences number-of-wiggle-subsequences.cpp)
add_executable(design-an-ordered-stream design-an-ordered-stream.cpp)
add_executable(range-module range-module.cpp)
add_executable(sort-items-by-groups-wrt-dependencies sort-items-by-groups-wrt-dependencies.cpp)
add_executable(min-cost-to-sort-an-array-matrix min-cost-to-sort-an-array-matrix.cpp)
add_executable(earliest-possible-day-of-full-bloom-1 earliest-possible-day-of-full-bloom-1.cpp)
add_executable(min-total-dist-travelled min-total-dist-travelled.cpp)