add_executable(longest-consecutive-sequence-1 longest-consecutive-sequence-1.cpp)
add_executable(subarray-sums-divisible-by-k-1 subarray-sums-divisible-by-k-1.cpp)
add_executable(non-overlapping-intervals-1 non-overlapping-intervals-1.cpp)
add_executable(merge-intervals-1 merge-intervals-1.cpp)
add_executable(min-size-subarray-sum min-size-subarray-sum.cpp)
add_executable(duplicates-in-an-array duplicates-in-an-array.cpp)
add_executable(beautiful-array beautiful-array.cpp)
add_executable(gas-station-1 gas-station-1.cpp)
add_executable(task-scheduler-1 task-scheduler-1.cpp)
add_executable(h-index h-index.cpp)