add_executable(kth-largest-ele-in-array kth-largest-ele-in-array.cpp)
add_executable(sort-colours sort-colours.cpp)
add_executable(top-k-frequent-eles-1 top-k-frequent-eles-1.cpp)
add_executable(sort-characters-by-frequency sort-characters-by-frequency.cpp)
add_executable(custom-sort-string custom-sort-string.cpp)
add_executable(diagonal-traverse-2 diagonal-traverse-2.cpp)
add_executable(diagonal-sort-matrix diagonal-sort-matrix.cpp)
add_executable(largest-number largest-number.cpp)
add_executable(min-swaps-to-sort-array min-swaps-to-sort-array.cpp)
add_executable(wiggle-sort-2 wiggle-sort-2.cpp)