add_executable(search-rotated-sorted-array-1 search-rotated-sorted-array-1.cpp)
add_executable(first-and-last-position-of-ele-sorted-array first-and-last-position-of-ele-sorted-array.cpp)
add_executable(find-peak-ele find-peak-ele.cpp)
add_executable(kth-smallest-ele-sorted-matrix kth-smallest-ele-sorted-matrix.cpp)
add_executable(to-ship-packages-within-d-days to-ship-packages-within-d-days.cpp)
add_executable(koko-eating-bananas koko-eating-bananas.cpp)
add_executable(search-rotated-sorted-array-2 search-rotated-sorted-array-2.cpp)
add_executable(single-ele-in-sorted-array single-ele-in-sorted-array.cpp)
add_executable(find-right-interval find-right-interval.cpp)
add_executable(minimise-max-dist-to-gas-station minimise-max-dist-to-gas-station.cpp)