add_executable(merge-k-sorted-linkedlists merge-k-sorted-linkedlists.cpp)
add_executable(reverse-nodes-in-k-group reverse-nodes-in-k-group.cpp)
add_executable(lru-cache lru-cache.cpp)
add_executable(lfu-cache lfu-cache.cpp)
add_executable(reverse-alternate-k-nodes reverse-alternate-k-nodes.cpp)
add_executable(flattening-linkedlist flattening-linkedlist.cpp)
add_executable(split-linkedlist-into-parts split-linkedlist-into-parts.cpp)
add_executable(quicksort-single-linkedlist quicksort-single-linkedlist.cpp)
add_executable(insert-cyclic-sorted-list insert-cyclic-sorted-list.cpp)
add_executable(design-skip-list design-skip-list.cpp)