add_executable(defanging-an-ip-address-2 defanging-an-ip-address-2.cpp)
add_executable(backspace-string-compare backspace-string-compare.cpp)
add_executable(remove-all-adjacent-duplicates-string remove-all-adjacent-duplicates-string.cpp)
add_executable(design-front-middle-back-queue design-front-middle-back-queue.cpp)
add_executable(implement-queue-using-array-iterators implement-queue-using-array-iterators.cpp)
add_executable(valid-palindrome-2 valid-palindrome-2.cpp)
add_executable(palindrome-linked-list palindrome-linked-list.cpp)
add_executable(reverse-string reverse-string.cpp)
add_executable(number-of-students-unable-to-eat-lunch number-of-students-unable-to-eat-lunch.cpp)
add_executable(array-pairs-divisible-by-k array-pairs-divisible-by-k.cpp)