add_executable(binary-tree-level-order-traversal-2 binary-tree-level-order-traversal-2.cpp)
add_executable(lowest-common-ancestor-of-binary-tree lowest-common-ancestor-of-binary-tree.cpp)
add_executable(construct-binary-tree-from-preorder-inorder construct-binary-tree-from-preorder-inorder.cpp)
add_executable(binary-tree-right-side-view binary-tree-right-side-view.cpp)
add_executable(path-sum-4 path-sum-4.cpp)
add_executable(flatten-binary-tree-to-linked-list flatten-binary-tree-to-linked-list.cpp)
add_executable(populating-next-right-pointers-in-each-node populating-next-right-pointers-in-each-node.cpp)
add_executable(binary-tree-zigzag-level-order binary-tree-zigzag-level-order.cpp)
add_executable(sum-root-to-leaf-numbers sum-root-to-leaf-numbers.cpp)
add_executable(all-nodes-distance-k-in-binary-tree all-nodes-distance-k-in-binary-tree.cpp)