add_executable(split-array-largest-sum split-array-largest-sum.cpp)
add_executable(min-rotated-sorted-array-2 min-rotated-sorted-array-2.cpp)
add_executable(swim-in-raising-water swim-in-raising-water.cpp)
add_executable(kth-smallest-prime-fraction kth-smallest-prime-fraction.cpp)
add_executable(median-of-two-sorted-arrays-2 median-of-two-sorted-arrays-2.cpp)
add_executable(subsequence-with-min-score subsequence-with-min-score.cpp)
add_executable(minimise-max-diff-of-pairs minimise-max-diff-of-pairs.cpp)
add_executable(smallest-good-base smallest-good-base.cpp)
add_executable(max-value-at-given-index-bounded-array max-value-at-given-index-bounded-array.cpp)
add_executable(max-running-time-n-computers max-running-time-n-computers.cpp)