add_executable(binary-search binary-search.cpp)
add_executable(first-bad-version first-bad-version.cpp)
add_executable(search-insert-position search-insert-position.cpp)
add_executable(peak-index-mountain-array peak-index-mountain-array.cpp)
add_executable(guess-number-high-or-low guess-number-high-or-low.cpp)
add_executable(count-negative-numbers-sorted-matrix count-negative-numbers-sorted-matrix.cpp)
add_executable(sp-array-with-x-eles-greater-than-or-equal-x sp-array-with-x-eles-greater-than-or-equal-x.cpp)
add_executable(target-indicies-after-sorting-array target-indicies-after-sorting-array.cpp)
add_executable(if-n-and-its-double-exist if-n-and-its-double-exist.cpp)
add_executable(intersection-of-two-arrays-1 intersection-of-two-arrays-1.cpp)