add_executable(add-two-numbers add-two-numbers.cpp)
add_executable(remove-nth-node-from-end-of-list remove-nth-node-from-end-of-list.cpp)
add_executable(linkedlist-cycle-2 linkedlist-cycle-2.cpp)
add_executable(reorder-linkedlist reorder-linkedlist.cpp)
add_executable(sort-linkedlist sort-linkedlist.cpp)
add_executable(rotate-linkedlist rotate-linkedlist.cpp)
add_executable(odd-even-linkedlist odd-even-linkedlist.cpp)
add_executable(partition-linkedlist partition-linkedlist.cpp)
add_executable(swap-nodes-in-pairs swap-nodes-in-pairs.cpp)
add_executable(flatten-multilevel-double-linkedlist flatten-multilevel-double-linkedlist.cpp)