add_executable(longest-substring-without-rep-characters longest-substring-without-rep-characters.cpp)
add_executable(string-to-integer string-to-integer.cpp)
add_executable(longest-palindromic-substring longest-palindromic-substring.cpp)
add_executable(reverse-words-in-string reverse-words-in-string.cpp)
add_executable(zigzag-conversion zigzag-conversion.cpp)
add_executable(decode-string-1 decode-string-1.cpp)
add_executable(multiply-strings multiply-strings.cpp)
add_executable(repeated-string-match repeated-string-match.cpp)
add_executable(sentence-similarity-3 sentence-similarity-3.cpp)
add_executable(min-deletions-to-make-character-frequencies-unique min-deletions-to-make-character-frequencies-unique.cpp)