add_executable(longest-continuous-subarray-abs-less-than-or-equal-to-limit longest-continuous-subarray-abs-less-than-or-equal-to-limit.cpp)
add_executable(count-of-smaller-numbers-after-self count-of-smaller-numbers-after-self.cpp)
add_executable(min-number-of-k-consecutive-bit-flips min-number-of-k-consecutive-bit-flips.cpp)
add_executable(create-max-number-1 create-max-number-1.cpp)
add_executable(splitting-a-string-into-descending-consecutive-values splitting-a-string-into-descending-consecutive-values.cpp)
add_executable(subarray-eles-greater-than-threshold subarray-eles-greater-than-threshold.cpp)
add_executable(max-product-subarray max-product-subarray.cpp)
add_executable(smallest-k-length-subsequence-with-letter smallest-k-length-subsequence-with-letter.cpp)
add_executable(global-and-local-inversions global-and-local-inversions.cpp)
add_executable(max-fruit-selected-after-distributing-balance max-fruit-selected-after-distributing-balance.cpp)