add_executable(making-a-large-island making-a-large-island.cpp)
add_executable(shortest-path-in-grid-with-obstacles-removed shortest-path-in-grid-with-obstacles-removed.cpp)
add_executable(maximal-rectangle-1 maximal-rectangle-1.cpp)
add_executable(dungeon-game dungeon-game.cpp)
add_executable(sudoku-solver-2 sudoku-solver-2.cpp)
add_executable(cherry-pickup cherry-pickup.cpp)
add_executable(bricks-falling-when-hit bricks-falling-when-hit.cpp)
add_executable(shortest-path-to-get-all-keys-1 shortest-path-to-get-all-keys-1.cpp)
add_executable(cut-off-trees-for-golf-event cut-off-trees-for-golf-event.cpp)
add_executable(contain-virus contain-virus.cpp)
