add_executable(rotting-oranges-2 rotting-oranges-2.cpp)
add_executable(01-matrix-2 01-matrix-2.cpp)
add_executable(design-circular-deque-1 design-circular-deque-1.cpp)
add_executable(open-the-lock open-the-lock.cpp)
add_executable(wall-gates-and-guards wall-gates-and-guards.cpp)
add_executable(shortest-path-in-binary-matrix shortest-path-in-binary-matrix.cpp)
add_executable(min-operations-to-convert-number min-operations-to-convert-number.cpp)
add_executable(find-eventual-safe-states find-eventual-safe-states.cpp)
add_executable(bounded-queue-producer-consumer bounded-queue-producer-consumer.cpp)
add_executable(keys-and-rooms keys-and-rooms.cpp)