add_executable(flood-fill-1 flood-fill-1.cpp)
add_executable(island-perimter island-perimeter.cpp)
add_executable(reshape-the-matrix reshape-the-matrix.cpp)
add_executable(matrix-diagonal-sum matrix-diagonal-sum.cpp)
add_executable(transpose-matrix transpose-matrix.cpp)
add_executable(cells-with-odd-values cells-with-odd-values.cpp)
add_executable(flipping-an-image flipping-an-image.cpp)
add_executable(shift-2d-grid shift-2d-grid.cpp)
add_executable(available-captures-for-rook available-captures-for-rook.cpp)
add_executable(lucky-numbers-in-matrix lucky-numbers-in-matrix.cpp)