add_executable(design-circular-deque-2 design-circular-deque-2.cpp)
add_executable(max-consecutive-ones max-consecutive-ones.cpp)
add_executable(product-of-last-k-numbers product-of-last-k-numbers.cpp)
add_executable(jump-game-2 jump-game-2.cpp)
add_executable(longest-substring-without-repeating-characters longest-substring-without-repeating-characters.cpp)
add_executable(longest-continuous-subarray-abs-diff-less-than-or-equal-limit longest-continuous-subarray-abs-diff-less-than-or-equal-limit.cpp)
add_executable(continuous-subarrays continuous-subarrays.cpp)
add_executable(max-no-of-vowels-substring-of-given-length max-no-of-vowels-substring-of-given-length.cpp)
add_executable(delimited-string-substring-partition delimited-string-substring-partition.cpp)
add_executable(design-hit-counter design-hit-counter.cpp)