add_executable(stack-using-queue stack-using-queue.cpp)
add_executable(number-of-recent-calls number-of-recent-calls.cpp)
add_executable(first-unique-character-in-string-2 first-unique-character-in-string-2.cpp)
add_executable(time-needed-to-buy-tickets time-needed-to-buy-tickets.cpp)
add_executable(design-circular-queue design-circular-queue.cpp)
add_executable(moving-avg-from-data-stream moving-avg-from-data-stream.cpp)
add_executable(binary-tree-level-order-traversal-1 binary-tree-level-order-traversal-1.cpp)
add_executable(final-prices-with-sp-discount final-prices-with-sp-discount.cpp)
add_executable(reveal-cards-increasing-order reveal-cards-increasing-order.cpp)
add_executable(thread-safe-task-queue thread-safe-task-queue.cpp)