add_executable(valid-parentheses-2 valid-parentheses-2.cpp)
add_executable(min-stack min-stack.cpp)
add_executable(queue-using-stack queue-using-stack.cpp)
add_executable(remove-all-adjacent-duplicates-in-string remove-all-adjacent-duplicates-in-string.cpp)
add_executable(make-string-great make-string-great.cpp)
add_executable(backspace-string backspace-string.cpp)
add_executable(final-prices-with-special-discount final-prices-with-special-discount.cpp)
add_executable(crawler-log-folder crawler-log-folder.cpp)
add_executable(next-greater-element-1 next-greater-element-1.cpp)
add_executable(baseball-game baseball-game.cpp)