add_executable(max-xor-element-from-array max-xor-element-from-array.cpp)
add_executable(longest-awesome-substring-1 longest-awesome-substring-1.cpp)
add_executable(can-i-win-problem can-i-win-problem.cpp)
add_executable(min-work-sessions-to-finish-work min-work-sessions-to-finish-work.cpp)
add_executable(smallest-sufficient-team-problem smallest-sufficient-team-problem.cpp)
add_executable(number-of-valid-words-each-puzzle number-of-valid-words-each-puzzle.cpp)
add_executable(maximise-score-after-n-operations maximise-score-after-n-operations.cpp)
add_executable(distribute-rep-integers distribute-rep-integers.cpp)
add_executable(shortest-path-visiting-all-nodes shortest-path-visiting-all-nodes.cpp)
add_executable(max-and-sum-of-an-array max-and-sum-of-an-array.cpp)