add_executable(search-2d-matrix-2 search-2d-matrix-2.cpp)
add_executable(number-of-islands-1 number-of-islands-1.cpp)
add_executable(rotting-oranges-1 rotting-oranges-1.cpp)
add_executable(01-matrix-1 01-matrix-1.cpp)
add_executable(set-matrix-zeroes set-matrix-zeroes.cpp)
add_executable(word-search-3 word-search-3.cpp)
add_executable(maximal-square maximal-square.cpp)
add_executable(spiral-matrix-2 spiral-matrix-2.cpp)
add_executable(pacific-atlantic-waterflow pacific-atlantic-waterflow.cpp)
add_executable(count-submatrices-with-all-ones count-submatrices-with-all-ones.cpp)