add_executable(max-points-on-line-2 max-points-on-line-2.cpp)
add_executable(subarrays-with-k-different-integers-1 subarrays-with-k-different-integers-1.cpp)
add_executable(grid-illumination grid-illumination.cpp)
add_executable(first-missing-positive-2 first-missing-positive-2.cpp)
add_executable(min-window-substring-2 min-window-substring-2.cpp)
add_executable(subarray-sums-divisible-by-k-2 subarray-sums-divisible-by-k-2.cpp)
add_executable(longest-duplicate-substring longest-duplicate-substring.cpp)
add_executable(longest-awesome-substring-2 longest-awesome-substring-2.cpp)
add_executable(tuple-with-same-product tuple-with-same-product.cpp)
add_executable(maximise-number-of-bounded-subarrays maximise-number-of-bounded-subarrays.cpp)