#include <iostream>
#include <vector>
#include <unordered_map>
#include <algorithm>

using namespace std;

class Solution {
public:
    /*
     * -------------------------------------------------------------------------------------
     * CORE LOGIC: PRODUCT FREQUENCY MAP PERMUTATIONS
     * -------------------------------------------------------------------------------------
     * The objective is to find the total number of tuples $(a, b, c, d)$ such that 
     * $a \times b = c \times d$, where $a, b, c, d$ are distinct elements from an array 
     * containing unique positive integers.
     * 
     * 1. INTRA-PAIR COLLISION TRACKING:
     *    Instead of executing an expensive $O(N^4)$ search across every possible tuple combination,
     *    we break the problem down into independent pairs. We compute the product of every unique 
     *    pair $(nums[i], nums[j])$ where $i < j$. We store the frequencies of these products in an 
     *    `unordered_map<int, int>` called `productFrequencyMap`.
     * 
     * 2. COMBINATORIAL PERMUTATION IDENTITY:
     *    If a specific product value is generated by $F$ unique pairs, we can choose any 2 of 
     *    these pairs to form a valid matching configuration. The number of ways to pick 2 pairs 
     *    from $F$ available pairs is given by the combination formula:
     *    $\binom{F}{2} = \frac{F \times (F - 1)}{2}$
     * 
     * 3. EXPANDING PAIRS INTO TUPLES:
     *    For any two distinct pairs $\{a, b\}$ and $\{c, d\}$ that share the same product ($a \times b = c \times d$), 
     *    they can be arranged into exactly 8 distinct tuple permutations:
     *      1. (a, b, c, d)   2. (a, b, d, c)   3. (b, a, c, d)   4. (b, a, d, c)
     *      5. (c, d, a, b)   6. (c, d, b, a)   7. (d, c, a, b)   8. (d, c, b, a)
     *    
     *    Therefore, the total number of valid tuples contributed by a product with frequency $F$ is:
     *    $\text{Total Tuples} = \frac{F \times (F - 1)}{2} \times 8 = 4 \times F \times (F - 1)$
     * 
     * 4. ARRAY INTEGRITY CONDITIONS:
     *    Because the input elements are guaranteed to be unique, distinct pairs that generate 
     *    the same product will never share an individual element. This eliminates the need for 
     *    complex index overlap checks.
     */
    int tupleSameProduct(vector<int>& nums) {
        // Map stores: {Calculated_Product_Value -> Global_Occurrence_Frequency}
        unordered_map<int, int> productFrequencyMap;
        int n = static_cast<int>(nums.size());

        // Step 1: Calculate the product of every unique pair and log it in our map
        for (int i = 0; i < n; ++i) {
            for (int j = i + 1; j < n; ++j) {
                int currentProduct = nums[static_cast<size_t>(i)] * nums[static_cast<size_t>(j)];
                productFrequencyMap[currentProduct]++;
            }
        }

        int totalValidTuplesCount = 0;

        // Step 2 & 3: Apply combinatorial expansion rules across the logged frequencies
        for (const auto& entryPair : productFrequencyMap) {
            int frequency = entryPair.second;
            if (frequency >= 2) {
                totalValidTuplesCount += 4 * frequency * (frequency - 1);
            }
        }

        return totalValidTuplesCount;
    }
};

/*
 * COMPLEXITY PROFILE METRICS:
 * ----------------------------
 * TIME COMPLEXITY: O(N^2) - Where N represents the total number of elements in the array. 
 *                  The nested loops evaluate all unique pair combinations, resulting in 
 *                  $O(N^2)$ iterations. Hash map operations take amortized O(1) constant 
 *                  time per insertion, and the final linear sweep scales with the number 
 *                  of unique products, which is bounded by $O(N^2)$.
 *
 * SPACE COMPLEXITY: O(N^2) Auxiliary - The internal `productFrequencyMap` allocates space 
 *                   to track the occurrences of up to $\frac{N \times (N - 1)}{2}$ unique 
 *                   pair product variations in the worst-case scenario.
 */
int main() {
    int capacityCount;
    cout << "Enter the total number of unique elements in the array: ";
    if (!(cin >> capacityCount) || capacityCount < 4) {
        cout << "Invalid parameter configured. Minimum 4 unique elements required." << endl;
        return 1;
    }

    vector<int> nums(static_cast<size_t>(capacityCount));
    cout << "Enter the distinct array elements consecutively (Positive integers):\n";
    for (int i = 0; i < capacityCount; ++i) {
        cin >> nums[static_cast<size_t>(i)];
        if (nums[static_cast<size_t>(i)] <= 0) {
            cout << "Constraint Error: Elements must be positive integers." << endl;
            return 1;
        }
    }

    // Verify uniqueness constraint rule
    vector<int> sortingVerificationArray = nums;
    sort(sortingVerificationArray.begin(), sortingVerificationArray.end());
    for (size_t i = 1; i < sortingVerificationArray.size(); ++i) {
        if (sortingVerificationArray[i] == sortingVerificationArray[i - 1]) {
            cout << "Constraint Error: All elements inside the array must be strictly unique." << endl;
            return 1;
        }
    }

    Solution solver;
    cout << "\nExecuting pair combination counts and product frequency mappings..." << endl;
    int resultingTuplesCount = solver.tupleSameProduct(nums);

    cout << "Total number of valid matching permutations tuples (a,b,c,d) found: " << resultingTuplesCount << endl;

    return 0;
}