add_executable(binary-tree-max-path-sum binary-tree-max-path-sum.cpp)
add_executable(serialise-and-deserialise serialise-and-deserialise.cpp)
add_executable(vertical-order-traversal-binary-tree vertical-order-traversal-binary-tree.cpp)
add_executable(binary-tree-cameras binary-tree-cameras.cpp)
add_executable(recover-tree-from-preorder-traversal recover-tree-from-preorder-traversal.cpp)
add_executable(n-array-tree-level-order-max-width-bounds n-array-tree-level-order-max-width-bounds.cpp)
add_executable(all-possible-full-binary-trees all-possible-full-binary-trees.cpp)
add_executable(path-sum-5 path-sum-5.cpp)
add_executable(tree-distances-sum tree-distances-sum.cpp)
add_executable(kth-ancestor-of-tree-node kth-ancestor-of-tree-node.cpp)