add_executable(reverse-linkedlist reverse-linkedlist.cpp)
add_executable(merge-two-sorted-lists-2 merge-two-sorted-lists-2.cpp)
add_executable(linkedlist-cycle linkedlist-cycle.cpp)
add_executable(middle-of-linkedlist middle-of-linkedlist.cpp)
add_executable(delete-node-linkedlist delete-node-linkedlist.cpp)
add_executable(remove-linkedlist-eles remove-linkedlist-eles.cpp)
add_executable(palindrome-linkedlist palindrome-linkedlist.cpp)
add_executable(intersection-of-two-linkedlists intersection-of-two-linkedlists.cpp)
add_executable(remove-duplicates-sorted-linkedlist remove-duplicates-sorted-linkedlist.cpp)
add_executable(binary-to-integer-linkedlist binary-to-integer-linkedlist.cpp)