add_executable(largest-rectangle-in-histogram-2 largest-rectangle-in-histogram-2.cpp)
add_executable(trapping-rain-water-2 trapping-rain-water-2.cpp)
add_executable(maximal-rectangle-2 maximal-rectangle-2.cpp)
add_executable(basic-calculator basic-calculator.cpp)
add_executable(subarray-min-sum subarray-min-sum.cpp)
add_executable(max-score-of-good-subarray-1 max-score-of-good-subarray-1.cpp)
add_executable(parse-lisp-expression parse-lisp-expression.cpp)
add_executable(word-is-valid-after-substitution word-is-valid-after-substitution.cpp)
add_executable(number-of-atoms number-of-atoms.cpp)
add_executable(valid-parentheses-string valid-parentheses-string.cpp)