#include <iostream>

using namespace std;

/*
CORE LOGIC (LEGENDRE'S FORMULA + BINARY SEARCH ON RANGE):
- Let $f(x)$ be the number of trailing zeroes in $x!$. Trailing zeroes are generated by pairs of prime factors 2 and 5. 
  Since prime factor 5 always occurs less frequently than 2, the count of trailing zeroes is determined by the total number of 
  factors of 5 in $x!$.
- **Legendre's Formula**: The total exponent of a prime $p$ dividing $x!$ is given by:
  $$ f(x) = \sum_{i=1}^{\infty} \lfloor \frac{x}{5^i} \rfloor = \lfloor \frac{x}{5} \rfloor + \lfloor \frac{x}{25} \rfloor + \lfloor \frac{x}{125} \rfloor + \dots $$
- The function $f(x)$ is a monotonically increasing step function. Every time $x$ hits a multiple of 5, the number of zeroes jumps. 
  Importantly, if $x$ is a multiple of 25, 125, etc., it contributes multiple factors of 5, causing $f(x)$ to jump by more than 1 value 
  (e.g., jumping from 4 zeroes to 6 zeroes, skipping 5 completely).
- Therefore, the preimage size of a target value $k$ (the number of integers $x$ such that $f(x) == k$) can only ever be **5** or **0**.
  - If there is at least one number $x$ with exactly $k$ trailing zeroes, then the block of 5 numbers $[x, x+1, x+2, x+3, x+4]$ will all share 
    the exact same number of trailing zeroes.
  - If $k$ is skipped entirely due to a multi-factor jump, the preimage size is 0.
- **Algorithmic Strategy**:
  We can find the exact size by computing the boundary offsets: `preimageSize(k) = binarySearchRightBound(k) - binarySearchRightBound(k - 1)`.
  Where `binarySearchRightBound(k)` returns the largest integer $x$ such that $f(x) \le k$.
- **Search Bounds**:
  Since $x \approx 4k$ or $5k$, for a given $k$, a safe, strict upper bound for our binary search space is $5 \times (k + 1)$.

TIME COMPLEXITY: O(log K * log5(K)) - The binary search space takes O(log K) steps. In each step, Legendre's formula evaluates 
                 trailing zeroes in O(log5(K)) time by dividing by powers of 5.
SPACE COMPLEXITY: O(1) - The calculation executes completely in-place using scalar boundaries.
*/

// Helper function implementing Legendre's Formula to count trailing zeroes in x!
long long trailingZeroes(long long x) {
    long long count = 0;
    while (x > 0) {
        count += x / 5;
        x /= 5;
    }
    return count;
}

// Binary search helper to find the maximum x such that trailingZeroes(x) <= k
long long binarySearchRightBound(int k) {
    if (k < 0) return -1;
    
    long long low = 0;
    long long high = 5LL * (k + 1);
    long long result = 0;

    while (low <= high) {
        long long mid = low + (high - low) / 2;
        
        if (trailingZeroes(mid) <= k) {
            result = mid;       // Potential candidate, look for larger values to the right
            low = mid + 1;
        } else {
            high = mid - 1;     // Too many zeroes, shift search window left
        }
    }
    return result;
}

int preimageSizeFZF(int k) {
    // The size of the preimage is the difference between the upper boundary of k and the upper boundary of k-1
    return static_cast<int>(binarySearchRightBound(k) - binarySearchRightBound(k - 1));
}

int main() {
    int k;
    cout << "Enter the target number of trailing zeroes (K): ";
    cin >> k;

    if (k < 0) {
        cout << "Invalid input. K must be a non-negative integer." << endl;
        return 1;
    }

    int result = preimageSizeFZF(k);
    cout << "\nThe preimage size of the Factorial Zeroes Function for K = " << k << " is: " << result << endl;
    cout << "(Meaning there are exactly " << result << " integers whose factorials end with " << k << " zeroes.)" << endl;

    return 0;
}