add_executable(sort-array-by-parity sort-array-by-parity.cpp)
add_executable(valid-anagram-1 valid-anagram-1.cpp)
add_executable(rank-transform-of-array rank-transform-of-array.cpp)
add_executable(height-checker height-checker.cpp)
add_executable(make-two-arrays-equal-by-reversing-subarrays make-two-arrays-equal-by-reversing-subarrays.cpp)
add_executable(min-abs-diff min-abs-diff.cpp)
add_executable(sort-integers-number-of-1-bits sort-integers-number-of-1-bits.cpp)
add_executable(array-partition-1 array-partition-1.cpp)
add_executable(majority-ele-2 majority-ele-2.cpp)
add_executable(largest-perimeter-triangle largest-perimeter-triangle.cpp)