add_executable(max-depth-binary-tree max-depth-binary-tree.cpp)
add_executable(invert-binary-tree invert-binary-tree.cpp)
add_executable(same-tree same-tree.cpp)
add_executable(symmetric-tree symmetric-tree.cpp)
add_executable(diameter-of-binary-tree diameter-of-binary-tree.cpp)
add_executable(balanced-binary-tree balanced-binary-tree.cpp)
add_executable(path-sum-3 path-sum-3.cpp)
add_executable(merge-two-binary-trees merge-two-binary-trees.cpp)
add_executable(subtree-of-another-tree subtree-of-another-tree.cpp)
add_executable(binary-tree-inorder-traversal binary-tree-inorder-traversal.cpp)