add_executable(word-ladder-2 word-ladder-2.cpp)
add_executable(shortest-path-to-get-all-keys-2 shortest-path-to-get-all-keys-2.cpp)
add_executable(shortest-path-in-grid-with-obstacle-elimination shortest-path-in-grid-with-obstacle-elimination.cpp)
add_executable(min-moves-to-move-box-to-target min-moves-to-move-box-to-target.cpp)
add_executable(sliding-puzzle sliding-puzzle.cpp)
add_executable(jump-game-1 jump-game-1.cpp)
add_executable(cut-off-trees-golf-event cut-off-trees-golf-event.cpp)
add_executable(escape-a-large-maze escape-a-large-maze.cpp)
add_executable(min-cost-to-make-atleast-one-valid-path-in-grid min-cost-to-make-atleast-one-valid-path-in-grid.cpp)
add_executable(min-obstacle-removal-to-reach-corner min-obstacle-removal-to-reach-corner.cpp)