add_executable(two-sum-2 two-sum-2.cpp)
add_executable(first-unique-character-in-string-1 first-unique-character-in-string-1.cpp)
add_executable(intersection-of-two-arrays-3 intersection-of-two-arrays-3.cpp)
add_executable(has-duplicate-hashset has-duplicate-hashset.cpp)
add_executable(valid-anagram-2 valid-anagram-2.cpp)
add_executable(isomorphic-strings isomorphic-strings.cpp)
add_executable(word-pattern word-pattern.cpp)
add_executable(find-common-characters find-common-characters.cpp)
add_executable(destination-city destination-city.cpp)
add_executable(unique-number-of-occurences unique-number-of-occurences.cpp)