add_executable(sliding-window-maximum sliding-window-maximum.cpp)
add_executable(shortest-subarray-with-sum-atleast-k shortest-subarray-with-sum-atleast-k.cpp)
add_executable(constrained-subarray-sum constrained-subarray-sum.cpp)
add_executable(max-score-of-good-subarray-2 max-score-of-good-subarray-2.cpp)
add_executable(max-value-of-equation max-value-of-equation.cpp)
add_executable(create-max-number-2 create-max-number-2.cpp)
add_executable(min-window-substring min-window-substring.cpp)
add_executable(subarrays-with-k-different-integers-2 subarrays-with-k-different-integers-2.cpp)
add_executable(bounded-element-sequence-sum-variants bounded-element-sequence-sum-variants.cpp)
add_executable(subarray-with-eles-greater-than-varying-threshold subarray-with-eles-greater-than-varying-threshold.cpp)