add_executable(subsets-2 subsets-2.cpp)
add_executable(permutations permutations.cpp)
add_executable(combination-sum combination-sum.cpp)
add_executable(letter-combinations-of-phone-number letter-combinations-of-phone-number.cpp)
add_executable(generate-parentheses generate-parentheses.cpp)
add_executable(word-search-1 word-search-1.cpp)
add_executable(path-sum-2 path-sum-2.cpp)
add_executable(different-ways-to-add-parentheses different-ways-to-add-parentheses.cpp)
add_executable(partition-to-k-equal-sum-subsets partition-to-k-equal-sum-subsets.cpp)
add_executable(matchsticks-to-square matchsticks-to-square.cpp)