add_executable(subsets-2 subsets-2.cpp)
add_executable(permutations-1 permutations-1.cpp)
add_executable(combination-sum-1 combination-sum-1.cpp)
add_executable(letter-combinations-of-phone-number-1 letter-combinations-of-phone-number-1.cpp)
add_executable(generate-parentheses-1 generate-parentheses-1.cpp)
add_executable(word-search-1 word-search-1.cpp)
add_executable(path-sum-2 path-sum-2.cpp)
add_executable(different-ways-to-add-parentheses different-ways-to-add-parentheses.cpp)
add_executable(partition-to-k-equal-sum-subsets-1 partition-to-k-equal-sum-subsets-1.cpp)
add_executable(matchsticks-to-square-1 matchsticks-to-square-1.cpp)