add_executable(valid-palindrome-1 valid-palindrome-1.cpp)
add_executable(longest-common-prefix longest-common-prefix.cpp)
add_executable(implement-strStr-function implement-strStr-function.cpp)
add_executable(reverse-string-2 reverse-string-2.cpp)
add_executable(length-of-last-word length-of-last-word.cpp)
add_executable(valid-parentheses-1 valid-parentheses-1.cpp)
add_executable(reverse-words-in-string-3 reverse-words-in-string-3.cpp)
add_executable(fizz-buzz fizz-buzz.cpp)
add_executable(robot-return-to-origin robot-return-to-origin.cpp)
add_executable(defanging-an-ip-address-1 defanging-an-ip-address-1.cpp)