add_executable(next-greater-ele-2 next-greater-ele-2.cpp)
add_executable(daily-temperatures daily-temperatures.cpp)
add_executable(reverse-polish-notation reverse-polish-notation.cpp)
add_executable(decode-string-2 decode-string-2.cpp) 
add_executable(online-stock-span online-stock-span.cpp)
add_executable(min-remove-to-valid-parentheses min-remove-to-valid-parentheses.cpp)
add_executable(score-of-parentheses score-of-parentheses.cpp)
add_executable(simplify-path simplify-path.cpp)
add_executable(asteroid-collision asteroid-collision.cpp)
add_executable(remove-k-digits remove-k-digits.cpp)