add_executable(single-number-2 single-number-2.cpp)
add_executable(single-number-3 single-number-3.cpp)
add_executable(AND-of-numbers-range AND-of-numbers-range.cpp)
add_executable(max-product-of-word-lengths max-product-of-word-lengths.cpp)
add_executable(subsets-1 subsets-1.cpp)
add_executable(max-xor-of-two-numbers-in-array max-xor-of-two-numbers-in-array.cpp)
add_executable(integer-replacement integer-replacement.cpp)
add_executable(gray-code gray-code.cpp)
add_executable(sum-of-two-integers sum-of-two-integers.cpp)
add_executable(utf8-validation utf8-validation.cpp)